# Generated by Django 5.0.6 on 2024-12-28 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_incident_iteration_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='ack',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='ack_user',
        ),
        migrations.AlterField(
            model_name='incident',
            name='iteration',
            field=models.IntegerField(default=0, help_text='Niveau d’escalade de l’incident'),
        ),
        migrations.CreateModel(
            name='Acknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='DHT.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('incident', 'user')},
            },
        ),
    ]
