# Generated by Django 5.0.6 on 2025-01-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0004_remove_incident_ack_remove_incident_ack_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_token', models.CharField(blank=True, help_text='Token du bot Telegram', max_length=255, null=True)),
                ('smtp_host', models.CharField(blank=True, help_text='Adresse du serveur SMTP', max_length=255, null=True)),
                ('smtp_port', models.IntegerField(blank=True, help_text='Port SMTP', null=True)),
                ('smtp_user', models.CharField(blank=True, help_text='Utilisateur SMTP', max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, help_text='Mot de passe SMTP', max_length=255, null=True)),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Utiliser TLS pour SMTP')),
                ('alert_message', models.TextField(blank=True, help_text="Message d'alerte par défaut", null=True)),
            ],
        ),
    ]
