# Generated by Django 5.0.6 on 2025-01-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0005_globalalertsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalalertsettings',
            name='max_temperature',
            field=models.FloatField(blank=True, help_text='Température maximale pour déclencher une alerte', null=True),
        ),
        migrations.AddField(
            model_name='globalalertsettings',
            name='min_temperature',
            field=models.FloatField(blank=True, help_text='Température minimale pour déclencher une alerte', null=True),
        ),
    ]
