# Generated by Django 5.0.6 on 2025-01-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0006_globalalertsettings_max_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalalertsettings',
            name='alerts_enabled',
            field=models.BooleanField(default=True, help_text='Activer ou désactiver les alertes'),
        ),
    ]
